### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Eric-Sunxr** [aldahdooh/SFAD#2]
where is the file “multi_task_adv_selective_utils”？
error: ModuleNotFoundError: No module named 'multi_task_adv_selective_utils'

**Comment by aldahdooh** [comment]
@Eric-Sunxr thanks for your interest. The repository is updated. I invite you to see the SFAD code included in [Benchmark: Adversarial Examples (AEs) Detection](https://aldahdooh.github.io/detectors_review/)

**Comment by Eric-Sunxr** [comment]
Thanks!
